name: sri_guru_dig_vandanam
description: A new Flutter project to find Appaji's direction.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.0.1
  video_player: ^2.8.1
  camera: ^0.10.5+5
  http: ^1.1.0
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  intl: ^0.18.1
  # sun_flare: ^3.0.0
  vector_math: ^2.1.4
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  latlong2: ^0.9.0
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF" 